kind: live
title: Postgres

volumes:
  postgres:
    remote: storage:postgres
    mount: /project

jobs:
  postgres:
    action: gh:neuro-actions/postgres@v1.0.0
    args:
      db_user: neu.ro
      db_password: postgres
      db_dir_remote: ${{ volumes.postgres.remote }}
