kind: live
title: Postgres

volumes:
  postgres:
    remote: storage:postgres
    mount: /project

jobs:
  postgres:
    action: ws:action.yaml
    args:
      db_dir_remote: ${{ volumes.postgres.remote }}
